# version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    network_mode: "host"
#    networks:
#      - inception
    ports:
      - "3306:3306"
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    network_mode: "host"
    depends_on:
      - mariadb
    ports:
      - "9000:9000"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    network_mode: "host"
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"

volumes:
  mariadb_data:
  wordpress_data:


#networks:
#  inception:
#    driver: bridge

