# version: "3.8"

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb_XC
    restart: always
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "/usr/bin/mariadb-admin ping -h localhost -u root -p$$(cat /run/secrets/db_root_password) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_XC
    restart: always
    env_file: .env
    secrets:
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_user_password
      - wp_user_email
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php-fpm83 -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  nginx:
    build: ./requirements/nginx
    container_name: nginx_XC
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSfk https://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  adminer:
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile
    container_name: adminer_XC
    restart: unless-stopped
    ports:
      - "8080:8080"               # Expose to host for evaluator browser access
    networks:
      - inception
    depends_on:
      - mariadb


volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge

secrets:
  db_password:
    file: ../secrets/db_password
  db_root_password:
    file: ../secrets/db_root_password
  wp_admin_user:
    file: ../secrets/wp_admin_user
  wp_admin_password:
    file: ../secrets/wp_admin_password
  wp_admin_email:
    file: ../secrets/wp_admin_email
  wp_user:
    file: ../secrets/wp_user
  wp_user_password:
    file: ../secrets/wp_user_password
  wp_user_email:
    file: ../secrets/wp_user_email

